CREATE TABLE CUSTOMER_DETAILS (
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE,
    PHONE_NO NUMBER,
    ADDRESS VARCHAR2(50)
);
INSERT INTO CUSTOMER_DETAILS VALUES (1,'Abi','abi@gmail.com',1234567890,'Ramapuram Chennai');

INSERT INTO CUSTOMER_DETAILS VALUES (2,'Anu','anu@gmail.com',9876543210,'Madurai');

INSERT INTO CUSTOMER_DETAILS VALUES (3,'Ravi','ravi@gmail.com',9087654321,'Chengalpattu');

INSERT INTO CUSTOMER_DETAILS VALUES (4,'Karthik','karthik@gmail.com',9876543211,'Coimbatore');

INSERT INTO CUSTOMER_DETAILS VALUES (5,'Priya','priya@gmail.com',8765432109,'Salem');

-- READ

SELECT * FROM CUSTOMER_DETAILS;

-- UPDATE

UPDATE CUSTOMER_DETAILS
SET ADDRESS = 'Chennai'
WHERE CID = 5;

-- READ AFTER UPDATE

SELECT * FROM CUSTOMER_DETAILS;

-- DELETE

DELETE FROM CUSTOMER_DETAILS
WHERE CID = 4;

-- READ AFTER DELETE

SELECT * FROM CUSTOMER_DETAILS;

COMMIT;
