CREATE TABLE CUSTOMER_DETAILS (
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE,
    PHONE_NO NUMBER,
    ADDRESS VARCHAR2(50)
);
INSERT INTO CUSTOMER_DETAILS VALUES (1,'Abi','abi@gmail.com',1234567890,'Ramapuram Chennai');

INSERT INTO CUSTOMER_DETAILS VALUES (2,'Anu','anu@gmail.com',9876543210,'Madurai');

INSERT INTO CUSTOMER_DETAILS VALUES (3,'Ravi','ravi@gmail.com',9087654321,'Chengalpattu');

INSERT INTO CUSTOMER_DETAILS VALUES (4,'Karthik','karthik@gmail.com',9876543211,'Coimbatore');

INSERT INTO CUSTOMER_DETAILS VALUES (5,'Priya','priya@gmail.com',8765432109,'Salem');

INSERT INTO CUSTOMER_DETAILS VALUES (6,'Vignesh','vignesh@gmail.com',9012345678,'Namakkal');

INSERT INTO CUSTOMER_DETAILS VALUES (7,'Keerthana','keerthana@gmail.com',9123456789,'Karur');

INSERT INTO CUSTOMER_DETAILS VALUES (8,'Harish','harish@gmail.com',9234567890,'Kanchipuram');

INSERT INTO CUSTOMER_DETAILS VALUES (9,'Lavanya','lavanya@gmail.com',9345678901,'Cuddalore');

INSERT INTO CUSTOMER_DETAILS VALUES (10,'Pradeep','pradeep@gmail.com',9456789012,'Dindigul');

-- READ

SELECT * FROM CUSTOMER_DETAILS;

-- UPDATE

UPDATE CUSTOMER_DETAILS
SET ADDRESS = 'Chennai'
WHERE CID = 5;

-- READ AFTER UPDATE

SELECT * FROM CUSTOMER_DETAILS;

-- DELETE

DELETE FROM CUSTOMER_DETAILS
WHERE CID = 4;

-- READ AFTER DELETE

SELECT * FROM CUSTOMER_DETAILS;

COMMIT;
